run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - revive
    - misspell

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: exported
      - name: error-naming
      - name: error-return

issues:
  exclude-use-default: false
