run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - revive
    - govet
    - gocritic
    - gocyclo
    - unused

linters-settings:
  gocritic:
    enable-all: true
  gocyclo:
    min-complexity: 14
  revive:
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: exported
      - name: error-naming
      - name: error-return
      - name: atomic
      - name: bare-return
      - name: bool-literal-in-expr
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: datarace
      - name: deep-exit
      - name: early-return

issues:
  exclude-use-default: false
